import './globals.css';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Luis Cervantes | Portfolio',
  //TODO: Write the page description
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
